In [2]:
# modules
import os
import pandas as pd
import csv 

#File to load
file_to_load = "Data/final_dataset.csv"

#import data from spread sheet 
airport_data = pd.read_csv(file_to_load)
airport_data.head()

,year,month,carrier_name,airport_abbr,airport_name,city,state,total_number_flights,air_carrier_delay,weather_delay,national_aviation_system_delay,sercurity_delay,aircraft_arriving_late,flight_cancelled,flight_diverted
0,2018,September,Frontier Airlines Inc.,PBI,Palm Beach International Airport,West Palm Beach,FL,8.0,0.85,0.00,0.49,0.0,1.65,0.0,0.0
1,2018,September,Envoy Air,PBI,Palm Beach International Airport,West Palm Beach,FL,25.0,0.00,0.00,2.00,0.0,1.00,0.0,0.0
2,2018,September,United Air Lines Inc.,PBI,Palm Beach International Airport,West Palm Beach,FL,114.0,6.97,0.01,7.65,0.0,5.37,0.0,0.0
3,2018,September,Southwest Airlines Co.,PBI,Palm Beach International Airport,West Palm Beach,FL,143.0,8.14,0.00,1.49,0.0,15.36,0.0,1.0
4,2018,September,Endeavor Air Inc.,PBI,Palm Beach International Airport,West Palm Beach,FL,3.0,0.68,0.00,0.32,0.0,0.00,0.0,0.0

In [3]:
col_list = ["air_carrier_delay","weather_delay","national_aviation_system_delay",
            "sercurity_delay","aircraft_arriving_late","flight_cancelled","flight_diverted"]


airport_data['delay_sum'] = airport_data[col_list].sum(axis=1)
airport_data.head()

,year,month,carrier_name,airport_abbr,airport_name,city,state,total_number_flights,air_carrier_delay,weather_delay,national_aviation_system_delay,sercurity_delay,aircraft_arriving_late,flight_cancelled,flight_diverted,delay_sum
0,2018,September,Frontier Airlines Inc.,PBI,Palm Beach International Airport,West Palm Beach,FL,8.0,0.85,0.00,0.49,0.0,1.65,0.0,0.0,2.99
1,2018,September,Envoy Air,PBI,Palm Beach International Airport,West Palm Beach,FL,25.0,0.00,0.00,2.00,0.0,1.00,0.0,0.0,3.00
2,2018,September,United Air Lines Inc.,PBI,Palm Beach International Airport,West Palm Beach,FL,114.0,6.97,0.01,7.65,0.0,5.37,0.0,0.0,20.00
3,2018,September,Southwest Airlines Co.,PBI,Palm Beach International Airport,West Palm Beach,FL,143.0,8.14,0.00,1.49,0.0,15.36,0.0,1.0,25.99
4,2018,September,Endeavor Air Inc.,PBI,Palm Beach International Airport,West Palm Beach,FL,3.0,0.68,0.00,0.32,0.0,0.00,0.0,0.0,1.00

In [5]:
airport_groups = airport_data.groupby(['airport_name'])['total_number_flights']
airport_flighttotals = airport_groups.sum()

airport_df_totalflights = airport_flighttotals.reset_index()
airport_df_totalflights.head()

                      airport_name  total_number_flights
0        Aberdeen Regional Airport                 808.0
1         Abilene Regional Airport                2371.0
2  Abraham Lincoln Capital Airport                1898.0
3                     Adak Airport                 113.0
4             Akron-Canton Airport                7353.0

In [17]:
sorted_df = airport_df_totalflights.sort_values('total_number_flights',axis=0,ascending=False)
sorted_df.reset_index()
sorted_df.nlargest(25,'total_number_flights').reset_index()

,index,airport_name,total_number_flights
0,15,Atlanta International Airport,425255.0
1,63,Chicago O'hare International Airport,367499.0
2,77,Dallas/Fort Worth International Airport,319212.0
3,84,Denver International Airport,265815.0
4,57,Charlotte/Douglas International Airport,253116.0
5,185,Los Angeles International Airport,237975.0
6,44,Bush Intercontinental Airport,192696.0
7,247,Phoenix Sky Harbor International Airport,187507.0
8,283,San Francisco International Airport,186577.0
9,169,La Guardia Airport,185731.0
10,197,Mccarran International Airport,175983.0
11,206,Minneapolis/St. Paul International Airport,173738.0
12,86,Detroit Metro Airport,171856.0
13,34,Boston Logan International Airport,160831.0
14,291,Seattle/Tacoma International Airport,151959.0
15,233,Orlando International Airport,151263.0
16,274,Ronald Reagan Washington National Airport,150403.0
17,221,Newark Liberty International Airport,148412.0
18,152,John F. Kennedy International Airport,139021.0
19,246,Philadelphia International Airport,127967.0
20,279,Salt Lake City International Airport,123319.0
21,20,Baltimore / Washington International Airport,112429.0
22,108,Fort Lauderdale Hollywood International Airport,104383.0
23,282,San Diego International Airport,100665.0
24,203,Miami International Airport,94649.0